### PR TITLE
Resolve issue where Symfony2 collection parameters fail to be injected

### LINKED ISSUE #117: Array to string conversion error if a collection is passed as parameter to a context
In symfony 2 parameter.yml
```
parameters:
    mycollection.parameter:
        param: value1
        param2: value2
```
In behat.yml:
```
default:
    suites:
        default:
            contexts:
                - FeatureContext:
                    collection_parameter: "%%mycollection.parameter%%"
    extensions:
        Behat\Symfony2Extension: ~
```
FeatureContext

```
    public function __construct($parameters)
    {
    }
```
The problem probably come from [ServiceArgumentResolver](https://github.com/Behat/Symfony2Extension/blob/master/src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php#L115) where argument are treated like all arguments are scalar.

### PR DESCRIPTION
**Pull request by glennunipro**
This allows collection parameters defined in Symfony 2 to be injected. Fixes #117.

Currently, they fail to do so as there is a constraint that `preg_replace_callback` must return a string, but when resolving parameters from Symfony 2's container, you may either get back a `string`, `constant`, or `collection` (see [here](http://symfony.com/doc/2.8/service_container/parameters.html)).

I've swapped to using `preg_match` which will return a string, and I have changed the method signature of `replaceParameters` so that it returns the container value of the parameter. Then, if it is not a string, we return it to the caller (to avoid another issue passing it to `@escape`), otherwise the `escape` method is still called on it, and then returned.

### CODE REVIEW

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php [hunk 1]
```diff
@@ -60,10 +60,6 @@ public function resolveArguments(ReflectionClass $classReflection, array $argume
      */
     private function resolveArgument($argument)
     {
-        if (is_array($argument)) {
-            return array_map(array($this, 'resolveArgument'), $argument);
```
Comment (stof) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: this does not resolve argument recursively for arrays, which look wrong to me, as it does not allow services inside an array anymore

**Comment by stof** [comment]
and CI complains about your change

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php (hunk 1 above)
Comment (glennunipro) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: Very strange, I wasn't aware that was in the diff before I committed. I've re-instated that chunk, re-tested my scenarios locally and it's running. Unit tests aren't running on my machine right now so I'm relying on Travis.

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php [hunk 2]
```diff
@@ -108,15 +112,18 @@ private function getServiceName($argument)
...
+     * @param  string $key
+     * @return mixed
      */
-    private function replaceParameters(ContainerInterface $container, $argument)
+    private function replaceParameters(ContainerInterface $container, $key)
     {
-        return preg_replace_callback('/(?<!%)%([^%]+)%(?!%)/', function($matches) use ($container) {
-            return $container->getParameter($matches[1]);
-        }, $argument);
+        $cleanKey = preg_replace('/(?<!%)%([^%]+)%(?!%)/', '$1', $key);
```
Comment (sroze) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: You could probably use `preg_match` instead then

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php [hunk 3]
```diff
@@ -108,15 +112,18 @@ private function getServiceName($argument)
...
-     * @return string
+     * Sanitise the container key given by the Behat config file,
+     * and retrieve the parameter from the Container.
+     *
+     * @param  ContainerInterface $container
+     * @param  string $key
+     * @return mixed
      */
-    private function replaceParameters(ContainerInterface $container, $argument)
+    private function replaceParameters(ContainerInterface $container, $key)
```
Comment (sroze) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: As you change the behaviour of this method, can you also change its name? Also, why this name change (`key`) ?

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php [hunk 4]
```diff
@@ -74,9 +74,13 @@ private function resolveArgument($argument)
             return $service;
         }
 
-        $withParameters = $this->replaceParameters($container, $argument);
+        $resolvedParam = $this->replaceParameters($container, $argument);
 
-        return $this->escape($withParameters);
+        if (!is_string($resolvedParam)) {
```
Comment (sroze) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: You can use the ternary operator in the return instead of a if

Comment (glennunipro) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: I can use the ternary operator, but could you tell me the benefit in this case please?

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php (hunk 3 above)
Comment (glennunipro) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: No reason for changing the key, this PR was not in a ready state, still undergoing work as I was waiting for the test results from the CI process.

Has the behaviour of the method really changed? I don't think it has. I don't see the benefit of changing the name here, as it does still replace parameters, nothing new other than it will handle parameter collections.

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php (hunk 2 above)
Comment (glennunipro) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: Good point, as explained in my comment below, `preg_replace` worked for some cases, except I needed to check if there was a match before I proceeded. I have updated to use `preg_match`.

**Comment by glennunipro** [comment]
@stof / @sroze, could not get unit tests running yesterday so I left it to Travis to run the tests for me.

They failed as the `preg_replace` method was replacing all strings, and resolving everything that went through that method from the container. It should have instead only pulled values from the container which `preg_replace` affected, so I have swapped to `preg_match` and only pulling values from the container if `preg_match` caught something.

I've also written and tested a Behat scenario for this, where we have a collection-type parameter registered in Symfony's container. Added a couple of new methods to the `testapp`'s `FeatureContext` to handle this.

**Comment by glennunipro** [comment]
Done a bit of thinking about how to tackle this nicely, still don't think it's quite refined enough. The unit tests are now passing, and I've added in new ones to cover cases where container parameters are collections.

I made the decision to first check if the given argument is one entire substitution, and in that case, go directly to the container and request the parameter. That handles the case where an argument wants a collection parameter. If that is not the case, then similar logic as before occurs, exception and `Exception` is thrown if a collection-type parameter is reference in a partial string substitution, because it makes no sense to put a collection-type parameter in to a string.

The builds, except HHVM (``HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.``), are now passing. Any thoughts?

File: spec/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolverSpec.php [hunk 5]
```diff
@@ -23,12 +23,25 @@ function it_resolves_parameters_starting_and_ending_with_percentage_sign_if_they
         ContainerInterface $container
     ) {
         $container->getParameter('parameter')->willReturn('param_value');
+        $container->hasParameter('parameter')->wilLReturn(true);
```
Comment (pmalisak) [inline spec/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolverSpec.php]: typo

Comment (glennunipro) [inline spec/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolverSpec.php]: Nice spot. Resolved.

**Comment by sroze** [comment]
That's a good one, I'm happy with this. Regarding HHVM, as it's not supported anymore in Symfony 4, you can remove it from the `travis.yml` file :)

File: src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php (hunk 4 above)
Comment (sroze) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: To be fair, I won't argue about it, just my personal preference by reading the code. You can leave it this way.

Comment (glennunipro) [inline src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php]: Preferences are fine, I have no real preference either way; it was just the smallest issue on this PR at the time. My preference is that it's more readable to have a conditional block rather than a ternary in this case, equally I won't argue the point as I don't have any strong concerns either way.

Now the PR is complete, however, I don't mind changing it if that's the style for this repo.

**Comment by glennunipro** [comment]
@sroze thanks for confirming; I'll remove it in a separate PR as it's not a direct concern for this PR.

**Comment by sroze** [comment]
@stof are you happy with these changes as well?

**Comment by glennunipro** [comment]
Rebased, just to make the commit log cleaner.

@stof do you mind reviewing please?

**Comment by sroze** [comment]
Travis is blocked on PHP 5.3; will remove the support anyway. Thank you @glennunipro!
